### ISSUE TITLE
error: Wrong size for extra data

### ISSUE THREAD

**Issue by tazihad** [flathub/org.freedownloadmanager.Manager#7]
fdm updated to 6.19. Can you check what causing the error.

**Comment by RobotRoss** [comment]
+1, also having this issue

**Comment by ozky84** [comment]
Me too have this problem......Fdm only provide deb package sucks...
hate this because browser integration not working with flatpak......
I use Mageia 8.

**Comment by HappyHerwi** [comment]
There was a [pull request](https://github.com/flathub/org.freedownloadmanager.Manager/pull/11) to fix this issue. Kindly try it.
